### ISSUE TITLE
not well documented, need clarification

### ISSUE THREAD

**Issue by Faisal-nfl** [escpos/escpos#4]
Docs not giving actual example but using hard coded data like for some static report
```
<%= item "First item" %>
<%= item "Second item" %>
<%= item "Third item" %>
```
There should have been some actual object like an order with items etc.

Now how to pass an object report.erb from
`report = MyReport.new 'path/to/my_report.erb'`

than using multiple styles, its just showing **quad_text**
& exactly at which point it sends data to printer

**Comment by dieuit07** [comment]
In my case, I can not call method helper in MyReport (undefined method quad_text, ...)

**Comment by ffiebig** [comment]
As far as I understand, it doesn't. You can pass the information piping the output of the program directly to the printer ip or using cups.
`ruby print.rb | lp -d printer-name`
or
`ruby print.rb | nc <printer-ip> <port>`

**Comment by svoboda-jan** [comment]
Examples contain only necessary data to explain how the gem works. Objects like order are beyond the scope of this project, it is up to the developer to implement those.

The example report is actually not static, every time `item` is invoked it adds a number to the output text. It is just an example how to call report methods from the ERB templates.

This project does not send anything to the printer, its purpose is solely to encode data into ESC/POS. There are plans to implement this functionality, but as a separate project / gem.

**Comment by svoboda-jan** [comment]
I have updated the examples with a hash simulating an order and added another option to pass objects to the report in new version.
