### ISSUE TITLE
concatenating helpers?

### ISSUE THREAD

**Issue by spencertweedy** [escpos/escpos#8]
hi,

thank you for your effort in putting this great implementation together.

do you have any advice for concatenating helper methods?
for example, applying 'big' and 'center' to a string simultaneously.

thank you,
spencer

**Comment by martinGerez** [comment]
Have you tried nesting the helpers? I'm trying this but I don't have any thermal printer to test. The encoded string results without errors 🤔

**Comment by svoboda-jan** [comment]
Hi, it should work by just chaining them, calling one helper after another, like:
```ruby
<%= center big "Some text" %>
```
